### ISSUE TITLE
gulp dev, live or prod is not working

### ISSUE THREAD

**Issue by gvn182** [versatica/tryit-jssip#10]
gsaraiva@ITXENGCON01:/mnt/c/projetos/tryit-jssip-master$ gulp dev
[15:34:29] Using gulpfile /mnt/c/projetos/tryit-jssip-master/gulpfile.js
[15:34:29] Starting 'dev'...
[15:34:29] Starting 'env:dev'...
[15:34:29] setting "dev" environment
[15:34:29] Finished 'env:dev' after 6.51 ms
[15:34:29] Starting 'clean'...
[15:34:29] Finished 'clean' after 7.03 ms
[15:34:29] Starting 'lint'...
[15:34:31] Finished 'lint' after 1.91 s
[15:34:31] Starting 'bundle'...
[15:34:43] 'bundle' errored after 12 s
[15:34:43] Error: premature close
    at onclose (/mnt/c/projetos/tryit-jssip-master/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at Duplexify._destroy (/mnt/c/projetos/tryit-jssip-master/node_modules/duplexify/index.js:192:8)
    at /mnt/c/projetos/tryit-jssip-master/node_modules/duplexify/index.js:175:10
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
[15:34:43] 'dev' errored after 14 s

Any ideia?

**Comment by ibc** [comment]
Thanks. Fixed. It was due to a failing dependency.
