### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by davidcsi** [versatica/tryit-jssip#25]
Hello, following the readme, i'm doing

`npm install`

but i'm getting

```
# npm install
npm WARN deprecated material-ui@0.20.2: You can now upgrade to @material-ui/core
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! Linux 5.10.47-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log
```

The debug log ends with:

```
4751 error Linux 5.10.47-linuxkit
4752 error argv "/usr/bin/node" "/usr/bin/npm" "install"
4753 error node v8.10.0
4754 error npm  v3.5.2
4755 error code EMISSINGARG
4756 error typeerror Error: Missing required argument #1
4756 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4756 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4756 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4756 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4756 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4756 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4756 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4756 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4756 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4756 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4757 error typeerror This is an error with npm itself. Please report this error at:
4757 error typeerror     <http://github.com/npm/npm/issues>
4758 verbose exit [ 1, true ]
```

**Comment by ibc** [comment]
Looks like an error with npm itself. Honestly no idea, sorry.
